language: php

matrix:
    include:
        - php: 7.2
          dist: bionic
        - php: 7.3
          dist: bionic
        - php: 7.4
          dist: bionic
        - php: 8.0
          dist: bionic
    fast_finish: true

before_install:
    - echo "xdebug.overload_var_dump = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then travis_retry composer update --prefer-dist; fi
    - if [[ "$TRAVIS_PHP_VERSION" == "nightly" ]]; then travis_retry composer update --prefer-dist --ignore-platform-reqs; fi

script:
    - make test
